# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

line_break.disabled = false

# right prompt. You can customize this prompt to show information when the prompt is on the right side of the terminal.
right_format = "$kubernetes$aws${custom.aws_expires_gt_1h}${custom.aws_expires_lt_1h}"

# the order of the elements in the prompt
format = "$character$directory$all"

# the prompt character
[character]
format = "$symbol "
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"

[custom.aws_expires_gt_1h]
description = "Show aws session sso expiration time greater than 1h."
when = '[ $($HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 3600) != "" ]'
format = "[$output]($style) $symbol"
command = "$HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 3600"
style = "bold green"

[custom.aws_expires_lt_1h]
description = "Show aws session sso expiration time less than 1h. This is a warning"
when = '[ $($HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 0 3600) != "" ]'
format = "$symbol[$output]($style)"
style = "bold red"
command = "$HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 0 3600"

[aws]
format = "on [$symbol$profile(\\($region\\))]($style) "
style = "bold #FF9900"

[aws.profile_aliases]
"corujaengi" = "sandbox"
"corujaprod" = "prod"

[directory]
read_only = " 󰌾"

[kubernetes]
disabled = false
symbol = "⎈ "
format = "[$symbol$context(\\($namespace\\))]($style) "
style = "#326CE5 bold"

[gcloud]
disabled = true

[cmd_duration]
min_time = 100
show_milliseconds = true
min_time_to_notify = 10000
show_notifications = true
style = "bold yellow"

[battery]
disabled = true

[docker_context]
disabled = true

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[package]
symbol = "󰏗 "

[nodejs]
symbol = "[⬢](bold green) "

[golang]
symbol = "\uF8D0 a"
