# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

line_break.disabled = false

# right prompt. You can customize this prompt to show information when the prompt is on the right side of the terminal.
right_format="$kubernetes$aws${custom.aws_expires_gt_1h}${custom.aws_expires_lt_1h}"

# the order of the elements in the prompt
format = "$character$directory$all"

# the prompt character

[character]
format = "$symbol "
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"

[custom.aws_expires_gt_1h]
description = "Show aws session sso expiration time greater than 1h."
when = '[ $($HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 3600) != "" ]'
format = "[$output]($style) $symbol"
command = "$HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 3600"
style = "bold green"

[custom.aws_expires_lt_1h]
description = "Show aws session sso expiration time less than 1h. This is a warning"
when = '[ $($HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 0 3600) != "" ]'
format = "$symbol[$output]($style)"
style = "bold red"
command = "$HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 0 3600"

[aws]
format = "on [$symbol$profile(\\($region\\))]($style) "
style = "bold #FF9900" 

[aws.profile_aliases]
"corujaengi" = "sandbox"
"corujaprod" = "prod"

[directory]
read_only = " 󰌾"

[kubernetes]
disabled = false
symbol = "⎈ "
format = "[$symbol$context(\\($namespace\\))]($style) "
style = "#326CE5 bold"

[gcloud]
disabled = true

[cmd_duration]
min_time = 100
show_milliseconds = true
min_time_to_notify = 10000
show_notifications = true
style = "bold yellow"

[battery]
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
