# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Right prompt. You can customize this prompt to show information when the prompt is on the right side of the terminal.
right_format="$kubernetes$aws${custom.aws_expires_gt_1h}${custom.aws_expires_lt_1h}"

# The order of the elements in the prompt
format = "$directory$all"

[custom.aws_expires_gt_1h]
description = "show the aws time of the session expiry"
when = "[ $($HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 3600) != \"\" ]"
format = "[$symbol$output]($style)"
style = "bold green"
command = "$HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 3600"

[custom.aws_expires_lt_1h]
description = "show the aws time of the session expiry"
when = "[ $($HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 0 3600) != \"\" ]"
format = "[$symbol$output]($style)"
style = "bold red"
command = "$HOME/.dotfiles/scripts/show_aws_session_expires_prompt.sh 0 3600"

[aws]
disabled = false
symbol = ""
style = "bold #ff9900"
format = "aws [$symbol$profile(\\($region\\))]($style) "

[aws.profile_aliases]
"corujaengi" = "sandbox"
"corujaprod" = "prod"

[directory]
read_only = " 󰌾"

[kubernetes]
symbol = ""
disabled = false
format = "k8s [$symbol$context(\\($namespace\\))]($style) "
style = "bold #326CE5"

[[kubernetes.contexts]]
context_pattern = "prod"
style = "bold red"

[gcloud]
disabled = true

[character]
disabled = true 

[battery]
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
disabled = true

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
not_capable_style = "bold red"

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "
